default_config:

logger:
  default: info
  logs:
    custom_components.car_wash: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

binary_sensor:
  - platform: car_wash
    weather: weather.home_assistant

weather:
  - platform: demo
